default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_app_rails_development
  username: postgres
  password: 1d2@Dorcas

test:
  <<: *default
  database: blog_app_rails_test
  username: postgres
  password: 1d2@Dorcas

production:
  <<: *default
  database: blog_app_rails_production
  username: blog_app_rails
  password: <%= ENV["BLOG_APP_RAILS_DATABASE_PASSWORD"] %>
